/**
 * The global OpenCode plugin VDP generates (`vdp install`) into OpenCode's
 * global `plugins/` directory, where OpenCode auto-discovers it.
 *
 * The plugin runs inside OpenCode (under Bun), so it is one self-contained
 * file with Node built-in imports only, and it must never slow OpenCode down
 * or change what it does. Its design follows the runtime facts captured in
 * test/fixtures/opencode/README.md:
 *   - `event` is called without being awaited, synchronously in bus order, so
 *     the handler snapshots the few fields presence needs and returns at once;
 *     the snapshot joins one ordered queue;
 *   - one VDP process is in flight at a time, started with a fixed argument
 *     vector (absolute node, the VDP entry, `hook opencode`; no shell) and fed
 *     every queued snapshot on stdin as JSON lines, because one process per
 *     event cannot keep up with a turn. A failed, crashed or hung process
 *     (killed after a short timeout) never stops the entries after it;
 *   - every event is attributed to its root session before it leaves the
 *     queue. Parent links come from `session.created` / `session.updated`;
 *     an unknown session is looked up through the public client
 *     (`client.session.get`), following `parentID` with a depth bound and
 *     cycle protection. Entries wait, in order, while a lookup is pending,
 *     because the answer can arrive after the session's first events. A
 *     session in a cycle, past the bound, or whose chain ends in a missing
 *     session is dropped: it never creates a root marker;
 *   - `dispose` (awaited by OpenCode before it exits or reloads plugins, with
 *     no deadline of its own) ends every root this instance reported, after
 *     everything queued before it, and drains for a bounded time. A reload
 *     ends a root with no event of its own, and events that keep arriving
 *     after `dispose` starts are ignored so they cannot revive an ended root.
 *     Nothing is coalesced, lifecycle ends included.
 */

/** First line of every generated plugin: proof that VDP owns the file. */
export const OPENCODE_PLUGIN_HEADER =
  '// vibecoder-discord-presence: OpenCode plugin generated by `vdp install`.';

/** The plugin's file name inside OpenCode's global `plugins/` directory. */
export const OPENCODE_PLUGIN_FILE = 'vibecoder-discord-presence.js';

export interface OpenCodePluginOptions {
  /** The fixed argument vector of the VDP process: executable first, no shell. */
  command: readonly string[];
  /** Kill a VDP process that has not exited after this long. */
  childTimeoutMs?: number;
  /** How long `dispose` waits for the queue to drain. */
  drainMs?: number;
  /** How long one public-client session lookup may take. */
  lookupTimeoutMs?: number;
  /** How long a failed (not missing) lookup is remembered before it is retried. */
  lookupRetryMs?: number;
}

export const OPENCODE_CHILD_TIMEOUT_MS = 3000;
export const OPENCODE_DRAIN_MS = 4000;
export const OPENCODE_LOOKUP_TIMEOUT_MS = 2000;
export const OPENCODE_LOOKUP_RETRY_MS = 30_000;
/** Parent links followed before a session is treated as unresolvable. */
export const OPENCODE_MAX_DEPTH = 8;
/** Snapshots handed to one VDP process at most. */
export const OPENCODE_MAX_BATCH = 200;

/** Whether file content is a plugin VDP generated (and may replace or delete). */
export function isOwnedPlugin(content: string): boolean {
  const text = content.charCodeAt(0) === 0xfeff ? content.slice(1) : content;
  return text.split(/\r?\n/, 1)[0] === OPENCODE_PLUGIN_HEADER;
}

/** The plugin source. Every value is embedded as a JSON literal, never as code. */
export function renderOpenCodePlugin(options: OpenCodePluginOptions): string {
  const constants = [
    `const COMMAND = ${JSON.stringify(options.command)};`,
    `const CHILD_TIMEOUT_MS = ${options.childTimeoutMs ?? OPENCODE_CHILD_TIMEOUT_MS};`,
    `const DRAIN_MS = ${options.drainMs ?? OPENCODE_DRAIN_MS};`,
    `const LOOKUP_TIMEOUT_MS = ${options.lookupTimeoutMs ?? OPENCODE_LOOKUP_TIMEOUT_MS};`,
    `const LOOKUP_RETRY_MS = ${options.lookupRetryMs ?? OPENCODE_LOOKUP_RETRY_MS};`,
    `const MAX_DEPTH = ${OPENCODE_MAX_DEPTH};`,
    `const MAX_BATCH = ${OPENCODE_MAX_BATCH};`,
  ].join('\n');
  return `${OPENCODE_PLUGIN_HEADER}
// Do not edit: \`vdp install\` rewrites this file and \`vdp uninstall\` removes it.
// It reports what OpenCode is doing to vibecoder-discord-presence, which shows
// it on Discord. It never changes what OpenCode does.
import { spawn } from 'node:child_process';

${constants}
${PLUGIN_BODY}`;
}

/** The plugin body: plain JavaScript, kept free of template-literal syntax. */
const PLUGIN_BODY = String.raw`
const str = (v) => (typeof v === 'string' && v !== '' ? v : undefined);
const num = (v) => (typeof v === 'number' && Number.isFinite(v) ? v : undefined);
const obj = (v) => (typeof v === 'object' && v !== null ? v : {});

export const VibecoderDiscordPresence = async (input) => {
  const cwd = str(obj(input).directory);
  const client = obj(input).client;

  const parents = new Map(); // session id -> parent id, or null for a root
  const roots = new Map(); // session id -> its root id, once known
  const missing = new Map(); // session id -> until when it counts as unresolvable
  const lookups = new Set(); // session ids being looked up
  const reported = new Set(); // roots this instance has sent events for
  const toolStates = new Map(); // call id -> last tool state sent
  const queue = [];
  let inFlight = false;
  let disposing = false;
  let drained = null;

  const learn = (info) => {
    const id = str(info.id);
    if (id && !parents.has(id)) parents.set(id, str(info.parentID) ?? null);
  };

  // The root of a session: its id, null when it cannot be resolved, or
  // undefined while a lookup is still pending.
  const rootOf = (id) => {
    if (roots.has(id)) return roots.get(id);
    const seen = new Set();
    let cursor = id;
    for (let depth = 0; depth <= MAX_DEPTH; depth++) {
      if (roots.has(cursor)) {
        roots.set(id, roots.get(cursor));
        return roots.get(cursor);
      }
      if (seen.has(cursor)) return null; // a cycle
      seen.add(cursor);
      if ((missing.get(cursor) ?? 0) > Date.now()) return null;
      if (!parents.has(cursor)) {
        lookup(cursor);
        return undefined;
      }
      const parent = parents.get(cursor);
      if (parent === null) {
        roots.set(id, cursor);
        return cursor;
      }
      cursor = parent;
    }
    return null; // deeper than the bound
  };

  const lookup = (id) => {
    if (lookups.has(id)) return;
    lookups.add(id);
    const settle = (parent, retryAfterMs) => {
      lookups.delete(id);
      if (parent !== undefined) {
        if (!parents.has(id)) parents.set(id, parent);
      } else {
        missing.set(id, Date.now() + retryAfterMs);
      }
      pump();
    };
    let timer;
    const timeout = new Promise((resolve) => {
      timer = setTimeout(() => resolve({ timedOut: true }), LOOKUP_TIMEOUT_MS);
    });
    Promise.resolve()
      .then(() => Promise.race([client.session.get({ path: { id } }), timeout]))
      .then(
        (res) => {
          clearTimeout(timer);
          const info = obj(obj(res).data);
          const notFound =
            obj(obj(res).error).name === 'NotFoundError' || obj(obj(res).response).status === 404;
          if (str(info.id) === id) settle(str(info.parentID) ?? null);
          // A missing session stays missing; a slow or failed call is retried later.
          else settle(undefined, notFound ? Infinity : LOOKUP_RETRY_MS);
        },
        () => {
          clearTimeout(timer);
          settle(undefined, LOOKUP_RETRY_MS);
        },
      );
  };

  const deliver = (batch) => {
    inFlight = true;
    let finished = false;
    let timer;
    const finish = () => {
      if (finished) return;
      finished = true;
      clearTimeout(timer);
      inFlight = false;
      pump();
    };
    let child;
    try {
      child = spawn(COMMAND[0], COMMAND.slice(1), {
        stdio: ['pipe', 'ignore', 'ignore'],
        shell: false,
        windowsHide: true,
      });
    } catch {
      finish();
      return;
    }
    timer = setTimeout(() => {
      try {
        child.kill();
      } catch {
        // already gone
      }
      finish();
    }, CHILD_TIMEOUT_MS);
    child.on('error', finish);
    child.on('exit', finish);
    try {
      child.stdin.on('error', () => {});
      child.stdin.end(batch.map((line) => JSON.stringify(line)).join('\n') + '\n');
    } catch {
      // the exit or error handler moves the queue on
    }
  };

  // Send the longest in-order run of the queue whose roots are known.
  const pump = () => {
    if (inFlight) return;
    const batch = [];
    while (queue.length > 0 && batch.length < MAX_BATCH) {
      const entry = queue[0];
      if (entry.endAll) {
        queue.shift();
        for (const root of reported) batch.push({ v: 1, type: 'vdp.end', root });
        reported.clear();
        continue;
      }
      const root = rootOf(entry.session);
      if (root === undefined) break; // its lookup is pending: keep the order
      queue.shift();
      if (root === null) continue; // never attributed, never a marker
      reported.add(root);
      batch.push({ ...entry.line, root });
    }
    if (batch.length > 0) deliver(batch);
    else if (queue.length === 0 && drained) drained();
  };

  const enqueue = (session, line) => {
    if (!session) return;
    queue.push({ session, line: { v: 1, ...line, session, cwd } });
    pump();
  };

  const onEvent = (event) => {
    const type = str(obj(event).type);
    const p = obj(obj(event).properties);
    switch (type) {
      case 'session.created':
      case 'session.updated':
      case 'session.deleted': {
        const info = obj(p.info);
        learn(info);
        const tokens = obj(info.tokens);
        return enqueue(str(info.id), {
          type,
          parent: str(info.parentID),
          output: num(tokens.output),
          cost: num(info.cost),
          model: str(obj(info.model).id),
        });
      }
      case 'session.status':
        return enqueue(str(p.sessionID), { type, status: str(obj(p.status).type) });
      case 'session.idle':
      case 'session.error':
        return enqueue(str(p.sessionID), { type });
      case 'message.updated': {
        const info = obj(p.info);
        return enqueue(str(info.sessionID), {
          type,
          message: str(info.id),
          role: str(info.role),
          model: str(info.modelID) ?? str(obj(info.model).modelID),
          output: num(obj(info.tokens).output),
          cost: num(info.cost),
        });
      }
      case 'message.part.updated': {
        const part = obj(p.part);
        if (part.type !== 'tool') return;
        const call = str(part.callID);
        const state = obj(part.state);
        const status = str(state.status);
        const file = str(obj(state.input).filePath);
        // A running tool repeats with every bit of output; only changes matter.
        const key = (status ?? '') + '\n' + (file ?? '');
        if (!call || toolStates.get(call) === key) return;
        if (status === 'completed' || status === 'error') toolStates.delete(call);
        else toolStates.set(call, key);
        return enqueue(str(part.sessionID) ?? str(p.sessionID), {
          type,
          call,
          tool: str(part.tool),
          state: status,
          file,
        });
      }
      case 'permission.asked':
      case 'permission.updated':
        return enqueue(str(p.sessionID), { type, request: str(p.id) });
      case 'permission.replied':
        return enqueue(str(p.sessionID), { type, request: str(p.requestID) ?? str(p.permissionID) });
    }
  };

  return {
    event: async ({ event } = {}) => {
      if (disposing) return;
      try {
        onEvent(event);
      } catch {
        // presence must never break OpenCode
      }
    },
    dispose: async () => {
      if (disposing) return;
      disposing = true;
      try {
        queue.push({ endAll: true });
        await new Promise((resolve) => {
          const timer = setTimeout(resolve, DRAIN_MS);
          drained = () => {
            clearTimeout(timer);
            resolve();
          };
          pump();
        });
      } catch {
        // presence must never hold OpenCode up
      }
    },
  };
};
`;
